name: app_ecommerce_admin
description: A new Flutter package project.
version: 0.0.1
publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  app_ecommerce_setup:
    path: ../app_ecommerce_setup
  easy_localization: ^3.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  go_router: ^4.3.0
  shimmer: ^2.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
